import type { Preset, PresetGroup } from './preset';

const defaultPreset: Readonly<Preset> = {
  name: '',
  wand: {
    actions_per_round: 1,
    deck_capacity: 26,
    reload_time: 20,
    shuffle_deck_when_empty: false,
    cast_delay: 10,
    mana_charge_speed: 1400,
    mana_max: 5000,
    spread: 0,
    name: '',
    pic: '',
    speed: 1,
  },
  spells: [],
  always: [],
};

const Kantele = {
  actions_per_round: 1,
  deck_capacity: 20,
  reload_time: 2,
  shuffle_deck_when_empty: false,
  cast_delay: 1,
  mana_charge_speed: 30,
  mana_max: 2,
  spread: 0,
  name: 'Kantele',
  pic: '',
  speed: 1,
};
const Swiftness = {
  actions_per_round: 1,
  deck_capacity: 19,
  reload_time: 0,
  shuffle_deck_when_empty: false,
  cast_delay: -20,
  mana_charge_speed: 900,
  mana_max: 650,
  spread: 0,
  name: 'Wand of Swiftness',
  pic: '',
  speed: 1.25,
};
const Multitudes = {
  actions_per_round: 26,
  deck_capacity: 26,
  reload_time: 24,
  shuffle_deck_when_empty: false,
  cast_delay: 5,
  mana_charge_speed: 500,
  mana_max: 1500,
  spread: 3,
  name: 'Wand of Multitudes',
  pic: '',
  speed: 1.5,
};

export const defaultWand = defaultPreset.wand;

export const defaultPresets: Array<PresetGroup> = [
  {
    name: 'Empty Wands',
    presets: [
      {
        name: 'Multitudes',
        wand: { ...Multitudes },
        spells: [],
        always: [],
      },
      {
        name: 'Swiftness Upgraded (25cap)',
        wand: { ...Swiftness, deck_capacity: 25 },
        spells: [],
        always: [],
      },
      {
        name: 'Swiftness',
        wand: { ...Swiftness },
        spells: [],
        always: [],
      },
      {
        name: 'Kantele',
        wand: { ...Kantele },
        spells: [],
        always: [],
      },
    ],
  },
  {
    name: 'Advanced Guide: Introduction to Greek Letter Spells',
    presets: [
      {
        name: 'Wand Refresh',
        wand: { ...defaultWand },
        spells: ['BURST_2', 'BLACK_HOLE', 'RESET', 'LARPA_CHAOS', 'NUKE'],
        always: [],
      },
      {
        name: 'Gamma',
        wand: { ...defaultWand },
        spells: [
          'MANA_REDUCE',
          'MANA_REDUCE',
          'BURST_2',
          'LIGHT_BULLET_TRIGGER',
          'GAMMA',
          'CHAINSAW',
          'RESET',
          'BLACK_HOLE_BIG',
        ],
        always: [],
      },
      {
        name: 'Mu 1',
        wand: { ...defaultWand },
        spells: [
          'EXPLOSIVE_PROJECTILE',
          'EXPLOSIVE_PROJECTILE',
          'MU',
          'LIGHT_BULLET',
        ],
        always: [],
      },
      {
        name: 'Mu 2',
        wand: { ...defaultWand },
        spells: [
          'MANA_REDUCE',
          'BURST_2',
          'GAMMA',
          'LIGHT_BULLET',
          'CHAINSAW',
          'RESET',
          'HOMING',
          'PIERCING_SHOT',
          'CLIPPING_SHOT',
          'LIFETIME',
          'CURSE_WITHER_EXPLOSION',
          'EXPLOSIVE_PROJECTILE',
          'EXPLOSIVE_PROJECTILE',
          'MU',
        ],
        always: [],
      },
      {
        name: 'Alpha',
        wand: { ...defaultWand },
        spells: [
          'ROCKET_TIER_3',
          'GAMMA',
          'BURST_2',
          'ALPHA',
          'RESET',
          'CHAINSAW',
          'RESET',
          'ORBIT_LARPA',
          'LARPA_CHAOS',
          'LARPA_DEATH',
          'MU',
        ],
        always: [],
      },
      {
        name: 'Tau',
        wand: { ...defaultWand },
        spells: [
          'BURST_2',
          'LONG_DISTANCE_CAST',
          'MANA_REDUCE',
          'MANA_REDUCE',
          'MANA_REDUCE',
          'NOLLA',
          'GAMMA',
          'BLACK_HOLE_DEATH_TRIGGER',
          'REGENERATION_FIELD',
          'NOLLA',
          'TELEPORT_PROJECTILE_STATIC',
          'CHAINSAW',
          'RESET',
          'TAU',
        ],
        always: [],
      },
    ],
  },
  {
    name: 'Expert Guide: Draw',
    presets: [
      {
        name: 'Spell Evaluation',
        wand: { ...defaultWand },
        spells: [
          'DAMAGE',
          'BURST_2',
          'BURST_2',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'SPEED',
          'LIGHT_BULLET',
          'NUKE',
        ],
        always: [],
      },
      {
        name: 'Wrapping 1',
        wand: { ...defaultWand },
        spells: [
          'BURST_2',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT',
        ],
        always: [],
      },
      {
        name: 'Wrapping 2',
        wand: { ...defaultWand },
        spells: [
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
        ],
        always: [],
      },
      {
        name: 'Wrapping 3',
        wand: { ...defaultWand },
        spells: [
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'LIGHT',
        ],
        always: [],
      },
      {
        name: 'Triggers',
        wand: { ...defaultWand },
        spells: [
          'HOMING',
          'PIERCING_SHOT',
          'LIGHT_BULLET_TRIGGER',
          'BURST_3',
          'DAMAGE',
          'DIGGER',
          'DIGGER',
          'DIGGER',
        ],
        always: [],
      },
    ],
  },
  {
    name: 'Expert Guide: Divide By Spells',
    presets: [
      {
        name: 'Simple Divides',
        wand: { ...defaultWand },
        spells: ['DIVIDE_10', 'LIGHT_BULLET'],
        always: [],
      },
      {
        name: 'Dividing a Modifier',
        wand: { ...defaultWand },
        spells: ['DIVIDE_10', 'DAMAGE', 'LIGHT_BULLET'],
        always: [],
      },
      {
        name: 'Discard Displacement',
        wand: { ...defaultWand },
        spells: [
          'BURST_2',
          'DIVIDE_2',
          'DAMAGE',
          'LIGHT_BULLET',
          'LIGHT_BULLET',
          'RESET',
        ],
        always: [],
      },
      {
        name: 'Mechanics of Multiple Divides',
        wand: { ...defaultWand },
        spells: ['DIVIDE_10', 'DIVIDE_4', 'LIGHT_BULLET'],
        always: [],
      },
      {
        name: 'Multiple Divides on a Modifier',
        wand: { ...defaultWand },
        spells: ['DIVIDE_10', 'DIVIDE_4', 'DAMAGE', 'LIGHT_BULLET'],
        always: [],
      },
      {
        name: 'Iteration limit',
        wand: { ...defaultWand },
        spells: [
          'BURST_2',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_10',
          'DAMAGE',
          'LIGHT_BULLET',
        ],
        always: [],
      },
      {
        name: 'Wrapping Strangeness',
        wand: { ...defaultWand },
        spells: [
          'BURST_4',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_10',
          'DAMAGE',
          'LIGHT_BULLET',
        ],
        always: [],
      },
    ],
  },
  {
    name: 'Expert Guide: Calling and Recursion',
    presets: [
      {
        name: 'Tau Example',
        wand: { ...defaultWand },
        spells: ['TAU', 'TAU', 'LIGHT_BULLET'],
        always: [],
      },
      {
        name: 'Omega example',
        wand: { ...defaultWand },
        spells: ['GAMMA', 'RESET', 'LIGHT_BULLET', 'OMEGA', 'OMEGA'],
        always: [],
      },
    ],
  },
  {
    name: 'Expert Guide: High Damage Wands with Spells to Power',
    presets: [
      {
        name: 'Spells to Power',
        wand: { ...defaultWand },
        spells: [
          'BURST_3',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_4',
          'DIVIDE_2',
          'DIVIDE_2',
          'MONEY_MAGIC',
          'DIVIDE_10',
          'RUBBER_BALL',
          'CHAINSAW',
          'BURST_2',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_4',
          'DIVIDE_2',
          'DIVIDE_2',
          'SPELLS_TO_POWER',
          'DIVIDE_10',
          'RUBBER_BALL',
        ],
        always: [],
      },
      {
        name: 'Crit',
        wand: { ...defaultWand },
        spells: [
          'BURST_3',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_4',
          'DIVIDE_2',
          'DIVIDE_2',
          'BLOOD_TO_POWER',
          'DIVIDE_10',
          'RUBBER_BALL',
          'LASER_LUMINOUS_DRILL',
          'BURST_4',
          'HOMING_ROTATE',
          'DIVIDE_10',
          'RUBBER_BALL',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_4',
          'DIVIDE_4',
          'SPELLS_TO_POWER',
          'MATERIAL_WATER',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_4',
          'DIVIDE_2',
          'DIVIDE_2',
          'HITFX_CRITICAL_WATER',
        ],
        always: [],
      },
      {
        name: 'Velocity Damage 1',
        wand: { ...defaultWand },
        spells: [
          'DIVIDE_10',
          'ACCELERATING_SHOT',
          'DIVIDE_2',
          'LIGHT_SHOT',
          'HOMING_ROTATE',
          'BLOOD_TO_POWER',
          'RUBBER_BALL',
        ],
        always: [],
      },
      {
        name: 'Velocity Damage 2',
        wand: { ...defaultWand },
        spells: [
          'BURST_3',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_4',
          'DIVIDE_4',
          'BLOOD_TO_POWER',
          'DIVIDE_10',
          'RUBBER_BALL',
          'LASER_LUMINOUS_DRILL',
          'BURST_2',
          'DIVIDE_4',
          'ACCELERATING_SHOT',
          'SPEED',
          'HOMING_ROTATE',
          'DIVIDE_10',
          'RUBBER_BALL',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_10',
          'SPELLS_TO_POWER',
          'MATERIAL_WATER',
          'DIVIDE_10',
          'DIVIDE_10',
          'DIVIDE_4',
          'DIVIDE_4',
          'HITFX_CRITICAL_WATER',
        ],
        always: [],
      },
    ],
  },
];
