/* Auto-generated file - last built: 2024-12-26T16:38:01.626135 */

export const extraEntities = [
  'data/entities/misc/bounce_spark.xml',
  'data/entities/misc/homing_accelerating.xml',
  'data/entities/misc/hitfx_gravity_field_enemy.xml',
  'data/entities/misc/essence_to_power.xml',
  'data/entities/misc/homing_cursor.xml',
  'data/entities/misc/clipping_shot.xml',
  'data/entities/misc/hitfx_explode_slime.xml',
  'data/entities/misc/blood_to_acid.xml',
  'data/entities/misc/bounce_small_explosion.xml',
  'data/entities/misc/larpa_death.xml',
  'data/entities/misc/bounce_explosion.xml',
  'data/entities/misc/spells_to_power.xml',
  'data/entities/misc/laser_emitter_wider.xml',
  'data/entities/misc/accelerating_shot.xml',
  'data/entities/misc/larpa_downwards.xml',
  'data/entities/misc/hitfx_tentacle_ray_enemy.xml',
  'data/entities/particles/gold_sparks.xml',
  'data/entities/particles/heavy_shot.xml',
  'data/entities/misc/random_explosion.xml',
  'data/entities/misc/hitfx_curse_wither_melee.xml',
  'data/entities/misc/decelerating_shot.xml',
  'data/entities/misc/hitfx_toxic_charm.xml',
  'data/entities/misc/larpa_upwards.xml',
  'data/entities/misc/explosion_tiny.xml',
  'data/entities/particles/light_shot.xml',
  'data/entities/misc/phasing_arc.xml',
  'data/entities/particles/tinyspark_red.xml',
  'data/entities/misc/orbit_larpa.xml',
  'data/entities/misc/piercing_shot.xml',
  'data/entities/misc/orbit_discs.xml',
  'data/entities/misc/spiraling_shot.xml',
  'data/entities/particles/tinyspark_purple_bright.xml',
  'data/entities/misc/explosion_remove.xml',
  'data/entities/misc/floating_arc.xml',
  'data/entities/misc/colour_purple.xml',
  'data/entities/misc/transmutation.xml',
  'data/entities/misc/zero_damage.xml',
  'data/entities/misc/rocket_octagon.xml',
  'data/entities/misc/fly_downwards.xml',
  'data/entities/misc/hitfx_critical_water.xml',
  'data/entities/misc/arc_electric.xml',
  'data/entities/misc/arc_gunpowder.xml',
  'data/entities/misc/homing.xml',
  'data/entities/misc/fireball_ray_line.xml',
  'data/entities/misc/fireball_ray.xml',
  'data/entities/particles/tinyspark_white.xml',
  'data/entities/misc/colour_red.xml',
  'data/entities/particles/tinyspark_orange.xml',
  'data/entities/misc/true_orbit.xml',
  'data/entities/misc/laser_emitter_ray.xml',
  'data/entities/misc/matter_eater.xml',
  'data/entities/particles/tinyspark_yellow.xml',
  'data/entities/misc/pingpong_path.xml',
  'data/entities/misc/avoiding_arc.xml',
  'data/entities/misc/rocket_downwards.xml',
  'data/entities/misc/arc_poison.xml',
  'data/entities/misc/crumbling_earth_projectile.xml',
  'data/entities/particles/tinyspark_white_weak.xml',
  'data/entities/misc/bounce_lightning.xml',
  'data/entities/misc/colour_rainbow.xml',
  'data/entities/particles/electricity.xml',
  'data/entities/misc/nolla.xml',
  'data/entities/misc/bounce_hole.xml',
  'data/entities/misc/area_damage.xml',
  'data/entities/misc/fly_upwards.xml',
  'data/entities/particles/freeze_charge.xml',
  'data/entities/misc/colour_blue.xml',
  'data/entities/particles/tinyspark_purple.xml',
  'data/entities/misc/hitfx_fireball_ray_enemy.xml',
  'data/entities/misc/homing_shooter.xml',
  'data/entities/misc/orbit_shot.xml',
  'data/entities/misc/homing_short.xml',
  'data/entities/misc/hitfx_explode_slime_giga.xml',
  'data/entities/misc/hitfx_curse_wither_projectile.xml',
  'data/entities/particles/tinyspark_white_small.xml',
  'data/entities/misc/homing_rotate.xml',
  'data/entities/particles/tinyspark_green.xml',
  'data/entities/misc/liquid_to_explosion.xml',
  'data/entities/misc/toxic_to_acid.xml',
  'data/entities/misc/hitfx_lightning_ray_enemy.xml',
  'data/entities/misc/lava_to_blood.xml',
  'data/entities/misc/effect_meteor_rain.xml',
  'data/entities/misc/homing_wand.xml',
  'data/entities/misc/orbit_fireballs.xml',
  'data/entities/misc/static_to_sand.xml',
  'data/entities/misc/hitfx_critical_oil.xml',
  'data/entities/misc/line_arc.xml',
  'data/entities/misc/water_to_poison.xml',
  'data/entities/misc/colour_invis.xml',
  'data/entities/misc/tentacle_ray.xml',
  'data/entities/misc/bounce_laser_emitter.xml',
  'data/entities/misc/larpa_chaos.xml',
  'data/entities/misc/quantum_split.xml',
  'data/entities/misc/sinewave.xml',
  'data/entities/misc/larpa_chaos_2.xml',
  'data/entities/misc/hitfx_curse_wither_electricity.xml',
  'data/entities/misc/bounce_larpa.xml',
  'data/entities/misc/hitfx_curse_wither_explosion.xml',
  'data/entities/misc/chain_shot.xml',
  'data/entities/misc/orbit_nukes.xml',
  'data/entities/misc/hitfx_explode_alcohol_giga.xml',
  'data/entities/misc/anti_homing.xml',
  'data/entities/misc/fizzle.xml',
  'data/entities/misc/lightning_ray.xml',
  'data/entities/misc/hitfx_curse.xml',
  'data/entities/misc/colour_orange.xml',
  'data/entities/misc/hitfx_explode_alcohol.xml',
  'data/entities/misc/light.xml',
  'data/entities/misc/burn.xml',
  'data/entities/misc/hitfx_critical_blood.xml',
  'data/entities/misc/colour_green.xml',
  'data/entities/misc/autoaim.xml',
  'data/entities/particles/blood_sparks.xml',
  'data/entities/misc/arc_fire.xml',
  'data/entities/misc/bounce_laser.xml',
  'data/entities/misc/colour_yellow.xml',
  'data/entities/misc/homing_area.xml',
  'data/entities/misc/chaotic_arc.xml',
  'data/entities/misc/horizontal_arc.xml',
  'data/entities/misc/energy_shield_shot.xml',
  'data/entities/misc/orbit_lasers.xml',
] as const;

export const actionIdExtraEntities = {
  'BOMB': [],
  'LIGHT_BULLET': [],
  'LIGHT_BULLET_TRIGGER': [],
  'LIGHT_BULLET_TRIGGER_2': [],
  'LIGHT_BULLET_TIMER': [],
  'BULLET': [],
  'BULLET_TRIGGER': [],
  'BULLET_TIMER': [],
  'HEAVY_BULLET': [],
  'HEAVY_BULLET_TRIGGER': [],
  'HEAVY_BULLET_TIMER': [],
  'AIR_BULLET': [],
  'SLOW_BULLET': [],
  'SLOW_BULLET_TRIGGER': [],
  'SLOW_BULLET_TIMER': [],
  'HOOK': [],
  'BLACK_HOLE': [],
  'BLACK_HOLE_DEATH_TRIGGER': [],
  'WHITE_HOLE': [],
  'BLACK_HOLE_BIG': [],
  'WHITE_HOLE_BIG': [],
  'BLACK_HOLE_GIGA': [],
  'WHITE_HOLE_GIGA': [],
  'TENTACLE_PORTAL': [],
  'SPITTER': [],
  'SPITTER_TIMER': [],
  'SPITTER_TIER_2': [],
  'SPITTER_TIER_2_TIMER': [],
  'SPITTER_TIER_3': [],
  'SPITTER_TIER_3_TIMER': [],
  'BUBBLESHOT': [],
  'BUBBLESHOT_TRIGGER': [],
  'DISC_BULLET': [],
  'DISC_BULLET_BIG': [],
  'DISC_BULLET_BIGGER': [],
  'BOUNCY_ORB': [],
  'BOUNCY_ORB_TIMER': [],
  'RUBBER_BALL': [],
  'ARROW': [],
  'POLLEN': [],
  'LANCE': [],
  'LANCE_HOLY': [],
  'ROCKET': [],
  'ROCKET_TIER_2': [],
  'ROCKET_TIER_3': [],
  'GRENADE': [],
  'GRENADE_TRIGGER': [],
  'GRENADE_TIER_2': [],
  'GRENADE_TIER_3': [],
  'GRENADE_ANTI': [],
  'GRENADE_LARGE': [],
  'MINE': [],
  'MINE_DEATH_TRIGGER': [],
  'PIPE_BOMB': [],
  'PIPE_BOMB_DEATH_TRIGGER': [],
  'FISH': [],
  'EXPLODING_DEER': [],
  'EXPLODING_DUCKS': [],
  'WORM_SHOT': [],
  'BOMB_DETONATOR': [],
  'LASER': [],
  'MEGALASER': [],
  'LIGHTNING': [],
  'BALL_LIGHTNING': [],
  'LASER_EMITTER': [],
  'LASER_EMITTER_FOUR': [],
  'LASER_EMITTER_CUTTER': [],
  'DIGGER': [],
  'POWERDIGGER': [],
  'CHAINSAW': [],
  'LUMINOUS_DRILL': [],
  'LASER_LUMINOUS_DRILL': [],
  'TENTACLE': [],
  'TENTACLE_TIMER': [],
  'HEAL_BULLET': [],
  'ANTIHEAL': [],
  'SPIRAL_SHOT': [],
  'MAGIC_SHIELD': [],
  'BIG_MAGIC_SHIELD': [],
  'CHAIN_BOLT': [],
  'FIREBALL': [],
  'METEOR': [],
  'FLAMETHROWER': [],
  'ICEBALL': [],
  'SLIMEBALL': [],
  'DARKFLAME': [],
  'MISSILE': [],
  'FUNKY_SPELL': [],
  'PEBBLE': [],
  'DYNAMITE': [],
  'GLITTER_BOMB': [],
  'BUCKSHOT': [],
  'FREEZING_GAZE': [],
  'GLOWING_BOLT': [],
  'SPORE_POD': [],
  'GLUE_SHOT': [],
  'BOMB_HOLY': [],
  'BOMB_HOLY_GIGA': [],
  'PROPANE_TANK': [],
  'BOMB_CART': [],
  'CURSED_ORB': [],
  'EXPANDING_ORB': [],
  'CRUMBLING_EARTH': [],
  'SUMMON_ROCK': [],
  'SUMMON_EGG': [],
  'SUMMON_HOLLOW_EGG': [],
  'TNTBOX': [],
  'TNTBOX_BIG': [],
  'SWARM_FLY': [],
  'SWARM_FIREBUG': [],
  'SWARM_WASP': [],
  'FRIEND_FLY': [],
  'ACIDSHOT': [],
  'THUNDERBALL': [],
  'FIREBOMB': [],
  'SOILBALL': [],
  'DEATH_CROSS': [],
  'DEATH_CROSS_BIG': [],
  'INFESTATION': [],
  'WALL_HORIZONTAL': [],
  'WALL_VERTICAL': [],
  'WALL_SQUARE': [],
  'TEMPORARY_WALL': [],
  'TEMPORARY_PLATFORM': [],
  'PURPLE_EXPLOSION_FIELD': [],
  'DELAYED_SPELL': [],
  'LONG_DISTANCE_CAST': [],
  'TELEPORT_CAST': [],
  'SUPER_TELEPORT_CAST': [],
  'CASTER_CAST': [],
  'MIST_RADIOACTIVE': [],
  'MIST_ALCOHOL': [],
  'MIST_SLIME': [],
  'MIST_BLOOD': [],
  'CIRCLE_FIRE': [],
  'CIRCLE_ACID': [],
  'CIRCLE_OIL': [],
  'CIRCLE_WATER': [],
  'MATERIAL_WATER': [],
  'MATERIAL_OIL': [],
  'MATERIAL_BLOOD': [],
  'MATERIAL_ACID': [],
  'MATERIAL_CEMENT': [],
  'TELEPORT_PROJECTILE': [],
  'TELEPORT_PROJECTILE_SHORT': [],
  'TELEPORT_PROJECTILE_STATIC': [],
  'SWAPPER_PROJECTILE': [],
  'TELEPORT_PROJECTILE_CLOSER': [],
  'NUKE': [],
  'NUKE_GIGA': [],
  'FIREWORK': [],
  'SUMMON_WANDGHOST': [],
  'TOUCH_GOLD': [],
  'TOUCH_WATER': [],
  'TOUCH_OIL': [],
  'TOUCH_ALCOHOL': [],
  'TOUCH_PISS': [],
  'TOUCH_GRASS': [],
  'TOUCH_BLOOD': [],
  'TOUCH_SMOKE': [],
  'DESTRUCTION': [],
  'MASS_POLYMORPH': [],
  'BURST_2': [],
  'BURST_3': [],
  'BURST_4': [],
  'BURST_8': [],
  'BURST_X': [],
  'SCATTER_2': [],
  'SCATTER_3': [],
  'SCATTER_4': [],
  'I_SHAPE': [],
  'Y_SHAPE': [],
  'T_SHAPE': [],
  'W_SHAPE': [],
  'CIRCLE_SHAPE': [],
  'PENTAGRAM_SHAPE': [],
  'I_SHOT': [],
  'Y_SHOT': [],
  'T_SHOT': [],
  'W_SHOT': [],
  'QUAD_SHOT': [],
  'PENTA_SHOT': [],
  'HEXA_SHOT': [],
  'SPREAD_REDUCE': [],
  'HEAVY_SPREAD': [],
  'RECHARGE': [],
  'LIFETIME': [],
  'LIFETIME_DOWN': [],
  'NOLLA': ['data/entities/misc/nolla.xml'],
  '': ['data/entities/misc/colour_invis.xml'],
  'SLOW_BUT_STEADY': [],
  'EXPLOSION_REMOVE': ['data/entities/misc/explosion_remove.xml'],
  'EXPLOSION_TINY': ['data/entities/misc/explosion_tiny.xml'],
  'LASER_EMITTER_WIDER': ['data/entities/misc/laser_emitter_wider.xml'],
  'MANA_REDUCE': [],
  'BLOOD_MAGIC': ['data/entities/particles/blood_sparks.xml'],
  'MONEY_MAGIC': ['data/entities/particles/gold_sparks.xml'],
  'BLOOD_TO_POWER': ['data/entities/particles/blood_sparks.xml'],
  'DUPLICATE': [],
  'QUANTUM_SPLIT': ['data/entities/misc/quantum_split.xml'],
  'GRAVITY': [],
  'GRAVITY_ANTI': [],
  'SINEWAVE': ['data/entities/misc/sinewave.xml'],
  'CHAOTIC_ARC': ['data/entities/misc/chaotic_arc.xml'],
  'PINGPONG_PATH': ['data/entities/misc/pingpong_path.xml'],
  'AVOIDING_ARC': ['data/entities/misc/avoiding_arc.xml'],
  'FLOATING_ARC': ['data/entities/misc/floating_arc.xml'],
  'FLY_DOWNWARDS': ['data/entities/misc/fly_downwards.xml'],
  'FLY_UPWARDS': ['data/entities/misc/fly_upwards.xml'],
  'HORIZONTAL_ARC': ['data/entities/misc/horizontal_arc.xml'],
  'LINE_ARC': ['data/entities/misc/line_arc.xml'],
  'ORBIT_SHOT': ['data/entities/misc/spiraling_shot.xml'],
  'SPIRALING_SHOT': ['data/entities/misc/orbit_shot.xml'],
  'PHASING_ARC': ['data/entities/misc/phasing_arc.xml'],
  'TRUE_ORBIT': ['data/entities/misc/true_orbit.xml'],
  'BOUNCE': [],
  'REMOVE_BOUNCE': [],
  'HOMING': ['data/entities/misc/homing.xml','data/entities/particles/tinyspark_white.xml'],
  'ANTI_HOMING': ['data/entities/misc/anti_homing.xml','data/entities/particles/tinyspark_white.xml'],
  'HOMING_WAND': ['data/entities/misc/homing_wand.xml','data/entities/particles/tinyspark_white.xml'],
  'HOMING_SHORT': ['data/entities/misc/homing_short.xml','data/entities/particles/tinyspark_white_weak.xml'],
  'HOMING_ROTATE': ['data/entities/misc/homing_rotate.xml','data/entities/particles/tinyspark_white.xml'],
  'HOMING_SHOOTER': ['data/entities/particles/tinyspark_white.xml','data/entities/misc/homing_shooter.xml'],
  'AUTOAIM': ['data/entities/misc/autoaim.xml'],
  'HOMING_ACCELERATING': ['data/entities/misc/homing_accelerating.xml','data/entities/particles/tinyspark_white_small.xml'],
  'HOMING_CURSOR': ['data/entities/misc/homing_cursor.xml','data/entities/particles/tinyspark_white.xml'],
  'HOMING_AREA': ['data/entities/misc/homing_area.xml','data/entities/particles/tinyspark_white.xml'],
  'PIERCING_SHOT': ['data/entities/misc/piercing_shot.xml'],
  'CLIPPING_SHOT': ['data/entities/misc/clipping_shot.xml'],
  'DAMAGE': ['data/entities/particles/tinyspark_yellow.xml'],
  'DAMAGE_RANDOM': ['data/entities/particles/tinyspark_yellow.xml'],
  'BLOODLUST': ['data/entities/particles/tinyspark_red.xml'],
  'DAMAGE_FOREVER': ['data/entities/particles/tinyspark_red.xml'],
  'CRITICAL_HIT': [],
  'AREA_DAMAGE': ['data/entities/misc/area_damage.xml'],
  'SPELLS_TO_POWER': ['data/entities/misc/spells_to_power.xml'],
  'ESSENCE_TO_POWER': ['data/entities/misc/essence_to_power.xml'],
  'ZERO_DAMAGE': ['data/entities/misc/zero_damage.xml','data/entities/particles/tinyspark_white_small.xml'],
  'HEAVY_SHOT': ['data/entities/particles/heavy_shot.xml'],
  'LIGHT_SHOT': ['data/entities/particles/light_shot.xml'],
  'KNOCKBACK': [],
  'RECOIL': [],
  'RECOIL_DAMPER': [],
  'SPEED': [],
  'ACCELERATING_SHOT': ['data/entities/misc/accelerating_shot.xml'],
  'DECELERATING_SHOT': ['data/entities/misc/decelerating_shot.xml'],
  'EXPLOSIVE_PROJECTILE': [],
  'CLUSTERMOD': [],
  'WATER_TO_POISON': ['data/entities/particles/tinyspark_purple.xml','data/entities/misc/water_to_poison.xml'],
  'BLOOD_TO_ACID': ['data/entities/misc/blood_to_acid.xml','data/entities/particles/tinyspark_red.xml'],
  'LAVA_TO_BLOOD': ['data/entities/misc/lava_to_blood.xml','data/entities/particles/tinyspark_orange.xml'],
  'LIQUID_TO_EXPLOSION': ['data/entities/particles/tinyspark_red.xml','data/entities/misc/liquid_to_explosion.xml'],
  'TOXIC_TO_ACID': ['data/entities/misc/toxic_to_acid.xml','data/entities/particles/tinyspark_green.xml'],
  'STATIC_TO_SAND': ['data/entities/misc/static_to_sand.xml','data/entities/particles/tinyspark_yellow.xml'],
  'TRANSMUTATION': ['data/entities/particles/tinyspark_purple_bright.xml','data/entities/misc/transmutation.xml'],
  'RANDOM_EXPLOSION': ['data/entities/particles/tinyspark_purple_bright.xml','data/entities/misc/random_explosion.xml'],
  'NECROMANCY': [],
  'LIGHT': ['data/entities/misc/light.xml'],
  'EXPLOSION': [],
  'EXPLOSION_LIGHT': [],
  'FIRE_BLAST': [],
  'POISON_BLAST': [],
  'ALCOHOL_BLAST': [],
  'THUNDER_BLAST': [],
  'BERSERK_FIELD': [],
  'POLYMORPH_FIELD': [],
  'CHAOS_POLYMORPH_FIELD': [],
  'ELECTROCUTION_FIELD': [],
  'FREEZE_FIELD': [],
  'REGENERATION_FIELD': [],
  'TELEPORTATION_FIELD': [],
  'LEVITATION_FIELD': [],
  'SHIELD_FIELD': [],
  'PROJECTILE_TRANSMUTATION_FIELD': [],
  'PROJECTILE_THUNDER_FIELD': [],
  'PROJECTILE_GRAVITY_FIELD': [],
  'VACUUM_POWDER': [],
  'VACUUM_LIQUID': [],
  'VACUUM_ENTITIES': [],
  'SEA_LAVA': [],
  'SEA_ALCOHOL': [],
  'SEA_OIL': [],
  'SEA_WATER': [],
  'SEA_SWAMP': [],
  'SEA_ACID': [],
  'SEA_ACID_GAS': [],
  'SEA_MIMIC': [],
  'CLOUD_WATER': [],
  'CLOUD_OIL': [],
  'CLOUD_BLOOD': [],
  'CLOUD_ACID': [],
  'CLOUD_THUNDER': [],
  'ELECTRIC_CHARGE': ['data/entities/particles/electricity.xml'],
  'MATTER_EATER': ['data/entities/misc/matter_eater.xml'],
  'FREEZE': ['data/entities/particles/freeze_charge.xml'],
  'HITFX_BURNING_CRITICAL_HIT': ['data/entities/particles/freeze_charge.xml'],
  'HITFX_CRITICAL_WATER': ['data/entities/misc/hitfx_critical_water.xml'],
  'HITFX_CRITICAL_OIL': ['data/entities/misc/hitfx_critical_oil.xml'],
  'HITFX_CRITICAL_BLOOD': ['data/entities/misc/hitfx_critical_blood.xml'],
  'HITFX_TOXIC_CHARM': ['data/entities/misc/hitfx_toxic_charm.xml'],
  'HITFX_EXPLOSION_SLIME': ['data/entities/misc/hitfx_explode_slime.xml'],
  'HITFX_EXPLOSION_SLIME_GIGA': ['data/entities/particles/tinyspark_purple.xml','data/entities/misc/hitfx_explode_slime_giga.xml'],
  'HITFX_EXPLOSION_ALCOHOL': ['data/entities/misc/hitfx_explode_alcohol.xml'],
  'HITFX_EXPLOSION_ALCOHOL_GIGA': ['data/entities/particles/tinyspark_orange.xml','data/entities/misc/hitfx_explode_alcohol_giga.xml'],
  'HITFX_PETRIFY': [],
  'ROCKET_DOWNWARDS': ['data/entities/misc/rocket_downwards.xml'],
  'ROCKET_OCTAGON': ['data/entities/misc/rocket_octagon.xml'],
  'FIZZLE': ['data/entities/misc/fizzle.xml'],
  'BOUNCE_EXPLOSION': ['data/entities/misc/bounce_explosion.xml'],
  'BOUNCE_SPARK': ['data/entities/misc/bounce_spark.xml'],
  'BOUNCE_LASER': ['data/entities/misc/bounce_laser.xml'],
  'BOUNCE_LASER_EMITTER': ['data/entities/misc/bounce_laser_emitter.xml'],
  'BOUNCE_LARPA': ['data/entities/misc/bounce_larpa.xml'],
  'BOUNCE_SMALL_EXPLOSION': ['data/entities/misc/bounce_small_explosion.xml'],
  'BOUNCE_LIGHTNING': ['data/entities/misc/bounce_lightning.xml'],
  'BOUNCE_HOLE': ['data/entities/misc/bounce_hole.xml'],
  'FIREBALL_RAY': ['data/entities/misc/fireball_ray.xml'],
  'LIGHTNING_RAY': ['data/entities/misc/lightning_ray.xml'],
  'TENTACLE_RAY': ['data/entities/misc/tentacle_ray.xml'],
  'LASER_EMITTER_RAY': ['data/entities/misc/laser_emitter_ray.xml'],
  'FIREBALL_RAY_LINE': ['data/entities/misc/fireball_ray_line.xml'],
  'FIREBALL_RAY_ENEMY': ['data/entities/misc/hitfx_fireball_ray_enemy.xml'],
  'LIGHTNING_RAY_ENEMY': ['data/entities/misc/hitfx_lightning_ray_enemy.xml'],
  'TENTACLE_RAY_ENEMY': ['data/entities/misc/hitfx_tentacle_ray_enemy.xml'],
  'GRAVITY_FIELD_ENEMY': ['data/entities/misc/hitfx_gravity_field_enemy.xml'],
  'CURSE': ['data/entities/misc/hitfx_curse.xml'],
  'CURSE_WITHER_PROJECTILE': ['data/entities/misc/hitfx_curse_wither_projectile.xml'],
  'CURSE_WITHER_EXPLOSION': ['data/entities/misc/hitfx_curse_wither_explosion.xml'],
  'CURSE_WITHER_MELEE': ['data/entities/misc/hitfx_curse_wither_melee.xml'],
  'CURSE_WITHER_ELECTRICITY': ['data/entities/misc/hitfx_curse_wither_electricity.xml'],
  'ORBIT_DISCS': ['data/entities/misc/orbit_discs.xml'],
  'ORBIT_FIREBALLS': ['data/entities/misc/orbit_fireballs.xml'],
  'ORBIT_NUKES': ['data/entities/misc/orbit_nukes.xml'],
  'ORBIT_LASERS': ['data/entities/misc/orbit_lasers.xml'],
  'ORBIT_LARPA': ['data/entities/misc/orbit_larpa.xml'],
  'CHAIN_SHOT': ['data/entities/misc/chain_shot.xml'],
  'ARC_ELECTRIC': ['data/entities/misc/arc_electric.xml'],
  'ARC_FIRE': ['data/entities/misc/arc_fire.xml'],
  'ARC_GUNPOWDER': ['data/entities/misc/arc_gunpowder.xml'],
  'ARC_POISON': ['data/entities/misc/arc_poison.xml'],
  'CRUMBLING_EARTH_PROJECTILE': ['data/entities/misc/crumbling_earth_projectile.xml'],
  'X_RAY': [],
  'UNSTABLE_GUNPOWDER': [],
  'ACID_TRAIL': [],
  'POISON_TRAIL': [],
  'OIL_TRAIL': [],
  'WATER_TRAIL': [],
  'GUNPOWDER_TRAIL': [],
  'FIRE_TRAIL': [],
  'BURN_TRAIL': ['data/entities/misc/burn.xml'],
  'TORCH': [],
  'TORCH_ELECTRIC': [],
  'ENERGY_SHIELD': [],
  'ENERGY_SHIELD_SECTOR': [],
  'ENERGY_SHIELD_SHOT': ['data/entities/misc/energy_shield_shot.xml'],
  'TINY_GHOST': [],
  'OCARINA_A': [],
  'OCARINA_B': [],
  'OCARINA_C': [],
  'OCARINA_D': [],
  'OCARINA_E': [],
  'OCARINA_F': [],
  'OCARINA_GSHARP': [],
  'OCARINA_A2': [],
  'KANTELE_A': [],
  'KANTELE_D': [],
  'KANTELE_DIS': [],
  'KANTELE_E': [],
  'KANTELE_G': [],
  'RANDOM_SPELL': [],
  'RANDOM_PROJECTILE': [],
  'RANDOM_MODIFIER': [],
  'RANDOM_STATIC_PROJECTILE': [],
  'DRAW_RANDOM': [],
  'DRAW_RANDOM_X3': [],
  'DRAW_3_RANDOM': [],
  'ALL_NUKES': [],
  'ALL_DISCS': [],
  'ALL_ROCKETS': [],
  'ALL_DEATHCROSSES': [],
  'ALL_BLACKHOLES': [],
  'ALL_ACID': [],
  'ALL_SPELLS': [],
  'SUMMON_PORTAL': [],
  'ADD_TRIGGER': [],
  'ADD_TIMER': [],
  'ADD_DEATH_TRIGGER': [],
  'LARPA_CHAOS': ['data/entities/misc/larpa_chaos.xml'],
  'LARPA_DOWNWARDS': ['data/entities/misc/larpa_downwards.xml'],
  'LARPA_UPWARDS': ['data/entities/misc/larpa_upwards.xml'],
  'LARPA_CHAOS_2': ['data/entities/misc/larpa_chaos_2.xml'],
  'LARPA_DEATH': ['data/entities/misc/larpa_death.xml'],
  'ALPHA': [],
  'GAMMA': [],
  'TAU': [],
  'OMEGA': [],
  'MU': [],
  'PHI': [],
  'SIGMA': [],
  'ZETA': [],
  'DIVIDE_2': [],
  'DIVIDE_3': [],
  'DIVIDE_4': [],
  'DIVIDE_10': [],
  'METEOR_RAIN': ['data/entities/misc/effect_meteor_rain.xml'],
  'WORM_RAIN': [],
  'RESET': [],
  'IF_ENEMY': [],
  'IF_PROJECTILE': [],
  'IF_HP': [],
  'IF_HALF': [],
  'IF_END': [],
  'IF_ELSE': [],
  'COLOUR_RED': ['data/entities/misc/colour_red.xml','data/entities/particles/tinyspark_red.xml'],
  'COLOUR_ORANGE': ['data/entities/particles/tinyspark_red.xml','data/entities/misc/colour_orange.xml'],
  'COLOUR_GREEN': ['data/entities/particles/tinyspark_red.xml','data/entities/misc/colour_green.xml'],
  'COLOUR_YELLOW': ['data/entities/misc/colour_yellow.xml','data/entities/particles/tinyspark_red.xml'],
  'COLOUR_PURPLE': ['data/entities/misc/colour_purple.xml','data/entities/particles/tinyspark_red.xml'],
  'COLOUR_BLUE': ['data/entities/particles/tinyspark_red.xml','data/entities/misc/colour_blue.xml'],
  'COLOUR_RAINBOW': ['data/entities/particles/tinyspark_red.xml','data/entities/misc/colour_rainbow.xml'],
  'COLOUR_INVIS': ['data/entities/misc/colour_invis.xml'],
  'RAINBOW_TRAIL': [],
  'CESSATION': [],
} as const;

/* vim: set readonly nomodifiable: Auto-generated file */