/* Auto-generated file - last built: 2024-12-24T14:07:01.843464 */

export const relatedProjectileIds = [
  'data/entities/projectiles/deck/lance.xml',
  'data/entities/projectiles/deck/orb_laseremitter_cutter.xml',
  'data/entities/projectiles/deck/grenade_large.xml',
  'data/entities/projectiles/deck/spitter_tier_3.xml',
  'data/entities/projectiles/bomb_cart.xml',
  'data/entities/projectiles/deck/grenade.xml',
  'data/entities/projectiles/deck/disc_bullet_big.xml',
  'data/entities/projectiles/deck/ocarina/ocarina_b.xml',
  'data/entities/projectiles/deck/kantele/kantele_d.xml',
  'data/entities/projectiles/deck/worm_shot.xml',
  'data/entities/projectiles/deck/bomb_detonator.xml',
  'data/entities/projectiles/deck/hook.xml',
  'data/entities/projectiles/deck/pollen.xml',
  'data/entities/projectiles/deck/vacuum_entities.xml',
  'data/entities/projectiles/deck/circle_acid.xml',
  'data/entities/projectiles/deck/touch_piss.xml',
  'data/entities/projectiles/deck/wand_ghost_player.xml',
  'data/entities/projectiles/deck/bullet_heavy.xml',
  'data/entities/projectiles/thunderball.xml',
  'data/entities/projectiles/deck/projectile_thunder_field.xml',
  'data/entities/projectiles/deck/sea_water.xml',
  'data/entities/projectiles/deck/black_hole.xml',
  'data/entities/projectiles/deck/cloud_blood.xml',
  'data/entities/projectiles/propane_tank.xml',
  'data/entities/projectiles/deck/acidshot.xml',
  'data/entities/projectiles/deck/teleport_projectile_closer.xml',
  'data/entities/projectiles/deck/kantele/kantele_a.xml',
  'data/entities/projectiles/deck/spore_pod.xml',
  'data/entities/projectiles/deck/sea_oil.xml',
  'data/entities/projectiles/deck/material_oil.xml',
  'data/entities/projectiles/deck/freezing_gaze_beam.xml',
  'data/entities/projectiles/bomb_holy_giga.xml',
  'data/entities/projectiles/deck/wall_vertical.xml',
  'data/entities/projectiles/deck/teleport_projectile_static.xml',
  'data/entities/projectiles/deck/death_cross.xml',
  'data/entities/projectiles/deck/rocket_tier_2.xml',
  'data/entities/projectiles/deck/buckshot_player.xml',
  'data/entities/projectiles/deck/rubber_ball.xml',
  'data/entities/projectiles/deck/exploding_deer.xml',
  'data/entities/projectiles/deck/wall_square.xml',
  'data/entities/projectiles/deck/explosion.xml',
  'data/entities/projectiles/deck/swarm_fly.xml',
  'data/entities/projectiles/deck/mine.xml',
  'data/entities/projectiles/deck/projectile_transmutation_field.xml',
  'data/entities/projectiles/deck/fireball.xml',
  'data/entities/projectiles/deck/chainsaw.xml',
  'data/entities/projectiles/chunk_of_soil.xml',
  'data/entities/projectiles/deck/teleport_cast.xml',
  'data/entities/projectiles/deck/lance_holy.xml',
  'data/entities/projectiles/deck/swarm_wasp.xml',
  'data/entities/projectiles/deck/super_teleport_cast.xml',
  'data/entities/projectiles/deck/material_blood.xml',
  'data/entities/projectiles/deck/vacuum_liquid.xml',
  'data/entities/projectiles/deck/glue_shot.xml',
  'data/entities/projectiles/deck/teleport_projectile.xml',
  'data/entities/projectiles/deck/delayed_spell.xml',
  'data/entities/projectiles/deck/kantele/kantele_e.xml',
  'data/entities/projectiles/deck/tentacle_portal.xml',
  'data/entities/projectiles/deck/heal_bullet.xml',
  'data/entities/projectiles/deck/sea_swamp.xml',
  'data/entities/projectiles/bomb_holy.xml',
  'data/entities/projectiles/deck/fireworks/firework_pink.xml',
  'data/entities/projectiles/deck/machinegun_bullet.xml',
  'data/entities/projectiles/deck/ocarina/ocarina_c.xml',
  'data/entities/projectiles/deck/rocket_player.xml',
  'data/entities/projectiles/deck/material_acid.xml',
  'data/entities/projectiles/deck/fireblast.xml',
  'data/entities/projectiles/deck/touch_gold.xml',
  'data/entities/projectiles/deck/disc_bullet_bigger.xml',
  'data/entities/projectiles/deck/mist_radioactive.xml',
  'data/entities/projectiles/deck/nuke.xml',
  'data/entities/projectiles/deck/ocarina/ocarina_a.xml',
  'data/entities/projectiles/deck/ocarina/ocarina_e.xml',
  'data/entities/projectiles/deck/arrow.xml',
  'data/entities/projectiles/deck/teleport_projectile_short.xml',
  'data/entities/projectiles/deck/white_hole.xml',
  'data/entities/projectiles/deck/sea_lava.xml',
  'data/entities/projectiles/deck/fish.xml',
  'data/entities/projectiles/deck/grenade_anti.xml',
  'data/entities/projectiles/deck/caster_cast.xml',
  'data/entities/projectiles/orb_cursed.xml',
  'data/entities/projectiles/deck/magic_shield_start.xml',
  'data/entities/projectiles/deck/flamethrower.xml',
  'data/entities/projectiles/deck/swarm_firebug.xml',
  'data/entities/projectiles/deck/touch_blood.xml',
  'data/entities/projectiles/deck/black_hole_giga.xml',
  'data/entities/projectiles/deck/freeze_field.xml',
  'data/entities/projectiles/deck/white_hole_big.xml',
  'data/entities/projectiles/deck/rock.xml',
  'data/entities/projectiles/deck/nuke_giga.xml',
  'data/entities/projectiles/deck/grenade_tier_2.xml',
  'data/entities/projectiles/deck/lightning.xml',
  'data/entities/projectiles/deck/chain_bolt.xml',
  'data/entities/projectiles/deck/alcohol_blast.xml',
  'data/entities/projectiles/deck/sea_acid.xml',
  'data/entities/projectiles/deck/circle_fire.xml',
  'data/entities/projectiles/deck/touch_alcohol.xml',
  'data/entities/projectiles/deck/rocket.xml',
  'data/entities/projectiles/deck/purple_explosion_field.xml',
  'data/entities/projectiles/deck/pipe_bomb.xml',
  'data/entities/projectiles/darkflame.xml',
  'data/entities/projectiles/deck/vacuum_powder.xml',
  'data/entities/projectiles/deck/light_bullet.xml',
  'data/entities/projectiles/deck/meteor.xml',
  'data/entities/projectiles/deck/kantele/kantele_g.xml',
  'data/entities/projectiles/deck/xray.xml',
  'data/entities/projectiles/deck/pebble_player.xml',
  'data/entities/projectiles/deck/teleportation_field.xml',
  'data/entities/projectiles/deck/thunder_blast.xml',
  'data/entities/animals/worm_big.xml',
  'data/entities/items/pickup/egg_monster.xml',
  'data/entities/projectiles/deck/death_cross_big.xml',
  'data/entities/projectiles/deck/explosion_light.xml',
  'data/entities/projectiles/deck/meteor_rain_meteor.xml',
  'data/entities/projectiles/deck/digger.xml',
  'data/entities/projectiles/deck/mist_alcohol.xml',
  'data/entities/projectiles/deck/ocarina/ocarina_a2.xml',
  'data/entities/projectiles/deck/black_hole_big.xml',
  'data/entities/projectiles/deck/luminous_drill.xml',
  'data/entities/projectiles/orb_expanding.xml',
  'data/entities/projectiles/deck/cloud_oil.xml',
  'data/entities/projectiles/deck/cloud_acid.xml',
  'data/entities/projectiles/deck/grenade_tier_3.xml',
  'data/entities/projectiles/deck/big_magic_shield_start.xml',
  'data/entities/projectiles/deck/tntbox.xml',
  'data/entities/projectiles/deck/touch_water.xml',
  'data/entities/projectiles/deck/glowing_bolt.xml',
  'data/entities/projectiles/deck/berserk_field.xml',
  'data/entities/projectiles/deck/long_distance_cast.xml',
  'data/entities/projectiles/deck/temporary_wall.xml',
  'data/entities/projectiles/deck/ocarina/ocarina_gsharp.xml',
  'data/entities/projectiles/deck/mist_slime.xml',
  'data/entities/projectiles/deck/infestation.xml',
  'data/entities/projectiles/deck/kantele/kantele_dis.xml',
  'data/entities/projectiles/deck/laser.xml',
  'data/entities/projectiles/deck/ball_lightning.xml',
  'data/entities/projectiles/deck/swapper.xml',
  'data/entities/projectiles/deck/friend_fly.xml',
  'data/entities/projectiles/deck/circle_oil.xml',
  'data/entities/projectiles/deck/electrocution_field.xml',
  'data/entities/projectiles/deck/touch_grass.xml',
  'data/entities/items/pickup/egg_hollow.xml',
  'data/entities/projectiles/deck/rocket_tier_3.xml',
  'data/entities/projectiles/deck/iceball.xml',
  'data/entities/projectiles/deck/regeneration_field.xml',
  'data/entities/projectiles/deck/temporary_platform.xml',
  'data/entities/projectiles/deck/bubbleshot.xml',
  'data/entities/projectiles/bomb.xml',
  'data/entities/projectiles/deck/light_bullet_air.xml',
  'data/entities/projectiles/deck/bullet.xml',
  'data/entities/projectiles/deck/mass_polymorph.xml',
  'data/entities/projectiles/deck/sea_acid_gas.xml',
  'data/entities/projectiles/deck/slime.xml',
  'data/entities/projectiles/deck/bouncy_orb.xml',
  'data/entities/projectiles/deck/crumbling_earth.xml',
  'data/entities/projectiles/deck/disc_bullet.xml',
  'data/entities/projectiles/deck/orb_laseremitter.xml',
  'data/entities/projectiles/deck/bullet_slow.xml',
  'data/entities/projectiles/deck/destruction.xml',
  'data/entities/projectiles/deck/polymorph_field.xml',
  'data/entities/projectiles/deck/projectile_gravity_field.xml',
  'data/entities/projectiles/deck/mist_blood.xml',
  'data/entities/projectiles/deck/ocarina/ocarina_d.xml',
  'data/entities/projectiles/deck/tntbox_big.xml',
  'data/entities/projectiles/deck/spiral_shot.xml',
  'data/entities/projectiles/deck/megalaser.xml',
  'data/entities/projectiles/deck/tentacle.xml',
  'data/entities/projectiles/deck/light_bullet_blue.xml',
  'data/entities/projectiles/deck/cloud_thunder.xml',
  'data/entities/projectiles/deck/spitter.xml',
  'data/entities/projectiles/deck/levitation_field.xml',
  'data/entities/projectiles/deck/powerdigger.xml',
  'data/entities/projectiles/deck/sea_alcohol.xml',
  'data/entities/projectiles/deck/circle_water.xml',
  'data/entities/projectiles/deck/material_water.xml',
  'data/entities/projectiles/deck/ocarina/ocarina_f.xml',
  'data/entities/projectiles/deck/cloud_water.xml',
  'data/entities/projectiles/deck/chaos_polymorph_field.xml',
  'data/entities/projectiles/deck/glitter_bomb.xml',
  'data/entities/projectiles/deck/firebomb.xml',
  'data/entities/projectiles/deck/wall_horizontal.xml',
  'data/entities/projectiles/deck/shield_field.xml',
  'data/entities/projectiles/deck/healhurt.xml',
  'data/entities/projectiles/deck/white_hole_giga.xml',
  'data/entities/projectiles/deck/touch_oil.xml',
  'data/entities/projectiles/deck/tnt.xml',
  'data/entities/projectiles/deck/poison_blast.xml',
  'data/entities/projectiles/deck/sea_mimic.xml',
  'data/entities/projectiles/deck/spitter_tier_2.xml',
  'data/entities/projectiles/deck/material_cement.xml',
  'data/entities/projectiles/deck/touch_smoke.xml',
] as const;

export const relatedAddedCounts = {
  'BOMB': ['data/entities/projectiles/bomb.xml'],
  'LIGHT_BULLET': ['data/entities/projectiles/deck/light_bullet.xml'],
  'LIGHT_BULLET_TRIGGER': ['data/entities/projectiles/deck/light_bullet.xml'],
  'LIGHT_BULLET_TRIGGER_2': ['data/entities/projectiles/deck/light_bullet_blue.xml'],
  'LIGHT_BULLET_TIMER': ['data/entities/projectiles/deck/light_bullet.xml'],
  'BULLET': ['data/entities/projectiles/deck/bullet.xml'],
  'BULLET_TRIGGER': ['data/entities/projectiles/deck/bullet.xml'],
  'BULLET_TIMER': ['data/entities/projectiles/deck/bullet.xml'],
  'HEAVY_BULLET': ['data/entities/projectiles/deck/bullet_heavy.xml'],
  'HEAVY_BULLET_TRIGGER': ['data/entities/projectiles/deck/bullet_heavy.xml'],
  'HEAVY_BULLET_TIMER': ['data/entities/projectiles/deck/bullet_heavy.xml'],
  'AIR_BULLET': ['data/entities/projectiles/deck/light_bullet_air.xml'],
  'SLOW_BULLET': ['data/entities/projectiles/deck/bullet_slow.xml'],
  'SLOW_BULLET_TRIGGER': ['data/entities/projectiles/deck/bullet_slow.xml'],
  'SLOW_BULLET_TIMER': ['data/entities/projectiles/deck/bullet_slow.xml'],
  'HOOK': ['data/entities/projectiles/deck/hook.xml'],
  'BLACK_HOLE': ['data/entities/projectiles/deck/black_hole.xml'],
  'BLACK_HOLE_DEATH_TRIGGER': ['data/entities/projectiles/deck/black_hole.xml'],
  'WHITE_HOLE': ['data/entities/projectiles/deck/white_hole.xml'],
  'BLACK_HOLE_BIG': ['data/entities/projectiles/deck/black_hole_big.xml'],
  'WHITE_HOLE_BIG': ['data/entities/projectiles/deck/white_hole_big.xml'],
  'BLACK_HOLE_GIGA': ['data/entities/projectiles/deck/black_hole_giga.xml'],
  'WHITE_HOLE_GIGA': ['data/entities/projectiles/deck/white_hole_giga.xml'],
  'TENTACLE_PORTAL': ['data/entities/projectiles/deck/tentacle_portal.xml'],
  'SPITTER': ['data/entities/projectiles/deck/spitter.xml'],
  'SPITTER_TIMER': ['data/entities/projectiles/deck/spitter.xml'],
  'SPITTER_TIER_2': ['data/entities/projectiles/deck/spitter_tier_2.xml'],
  'SPITTER_TIER_2_TIMER': ['data/entities/projectiles/deck/spitter_tier_2.xml'],
  'SPITTER_TIER_3': ['data/entities/projectiles/deck/spitter_tier_3.xml'],
  'SPITTER_TIER_3_TIMER': ['data/entities/projectiles/deck/spitter_tier_3.xml'],
  'BUBBLESHOT': ['data/entities/projectiles/deck/bubbleshot.xml'],
  'BUBBLESHOT_TRIGGER': ['data/entities/projectiles/deck/bubbleshot.xml'],
  'DISC_BULLET': ['data/entities/projectiles/deck/disc_bullet.xml'],
  'DISC_BULLET_BIG': ['data/entities/projectiles/deck/disc_bullet_big.xml'],
  'DISC_BULLET_BIGGER': ['data/entities/projectiles/deck/disc_bullet_bigger.xml'],
  'BOUNCY_ORB': ['data/entities/projectiles/deck/bouncy_orb.xml'],
  'BOUNCY_ORB_TIMER': ['data/entities/projectiles/deck/bouncy_orb.xml'],
  'RUBBER_BALL': ['data/entities/projectiles/deck/rubber_ball.xml'],
  'ARROW': ['data/entities/projectiles/deck/arrow.xml'],
  'POLLEN': ['data/entities/projectiles/deck/pollen.xml'],
  'LANCE': ['data/entities/projectiles/deck/lance.xml'],
  'LANCE_HOLY': ['data/entities/projectiles/deck/lance_holy.xml'],
  'ROCKET': ['data/entities/projectiles/deck/rocket.xml'],
  'ROCKET_TIER_2': ['data/entities/projectiles/deck/rocket_tier_2.xml'],
  'ROCKET_TIER_3': ['data/entities/projectiles/deck/rocket_tier_3.xml'],
  'GRENADE': ['data/entities/projectiles/deck/grenade.xml'],
  'GRENADE_TRIGGER': ['data/entities/projectiles/deck/grenade.xml'],
  'GRENADE_TIER_2': ['data/entities/projectiles/deck/grenade_tier_2.xml'],
  'GRENADE_TIER_3': ['data/entities/projectiles/deck/grenade_tier_3.xml'],
  'GRENADE_ANTI': ['data/entities/projectiles/deck/grenade_anti.xml'],
  'GRENADE_LARGE': ['data/entities/projectiles/deck/grenade_large.xml'],
  'MINE': ['data/entities/projectiles/deck/mine.xml'],
  'MINE_DEATH_TRIGGER': ['data/entities/projectiles/deck/mine.xml'],
  'PIPE_BOMB': ['data/entities/projectiles/deck/pipe_bomb.xml'],
  'PIPE_BOMB_DEATH_TRIGGER': ['data/entities/projectiles/deck/pipe_bomb.xml'],
  'FISH': ['data/entities/projectiles/deck/fish.xml'],
  'EXPLODING_DEER': ['data/entities/projectiles/deck/exploding_deer.xml'],
  'WORM_SHOT': ['data/entities/projectiles/deck/worm_shot.xml'],
  'BOMB_DETONATOR': ['data/entities/projectiles/deck/bomb_detonator.xml'],
  'LASER': ['data/entities/projectiles/deck/laser.xml'],
  'MEGALASER': ['data/entities/projectiles/deck/megalaser.xml'],
  'LIGHTNING': ['data/entities/projectiles/deck/lightning.xml'],
  'BALL_LIGHTNING': ['data/entities/projectiles/deck/ball_lightning.xml'],
  'LASER_EMITTER': ['data/entities/projectiles/deck/orb_laseremitter.xml'],
  'LASER_EMITTER_FOUR': ['data/entities/projectiles/deck/orb_laseremitter.xml'],
  'LASER_EMITTER_CUTTER': ['data/entities/projectiles/deck/orb_laseremitter_cutter.xml'],
  'DIGGER': ['data/entities/projectiles/deck/digger.xml'],
  'POWERDIGGER': ['data/entities/projectiles/deck/powerdigger.xml'],
  'CHAINSAW': ['data/entities/projectiles/deck/chainsaw.xml'],
  'LUMINOUS_DRILL': ['data/entities/projectiles/deck/luminous_drill.xml'],
  'LASER_LUMINOUS_DRILL': ['data/entities/projectiles/deck/luminous_drill.xml'],
  'TENTACLE': ['data/entities/projectiles/deck/tentacle.xml'],
  'TENTACLE_TIMER': ['data/entities/projectiles/deck/tentacle.xml'],
  'HEAL_BULLET': ['data/entities/projectiles/deck/heal_bullet.xml'],
  'ANTIHEAL': ['data/entities/projectiles/deck/healhurt.xml'],
  'SPIRAL_SHOT': ['data/entities/projectiles/deck/spiral_shot.xml'],
  'MAGIC_SHIELD': ['data/entities/projectiles/deck/magic_shield_start.xml'],
  'BIG_MAGIC_SHIELD': ['data/entities/projectiles/deck/big_magic_shield_start.xml'],
  'CHAIN_BOLT': ['data/entities/projectiles/deck/chain_bolt.xml'],
  'FIREBALL': ['data/entities/projectiles/deck/fireball.xml'],
  'METEOR': ['data/entities/projectiles/deck/meteor.xml'],
  'FLAMETHROWER': ['data/entities/projectiles/deck/flamethrower.xml'],
  'ICEBALL': ['data/entities/projectiles/deck/iceball.xml'],
  'SLIMEBALL': ['data/entities/projectiles/deck/slime.xml'],
  'DARKFLAME': ['data/entities/projectiles/darkflame.xml'],
  'MISSILE': ['data/entities/projectiles/deck/rocket_player.xml'],
  'FUNKY_SPELL': ['data/entities/projectiles/deck/machinegun_bullet.xml'],
  'PEBBLE': ['data/entities/projectiles/deck/pebble_player.xml'],
  'DYNAMITE': ['data/entities/projectiles/deck/tnt.xml'],
  'GLITTER_BOMB': ['data/entities/projectiles/deck/glitter_bomb.xml'],
  'BUCKSHOT': ['data/entities/projectiles/deck/buckshot_player.xml'],
  'FREEZING_GAZE': ['data/entities/projectiles/deck/freezing_gaze_beam.xml'],
  'GLOWING_BOLT': ['data/entities/projectiles/deck/glowing_bolt.xml'],
  'SPORE_POD': ['data/entities/projectiles/deck/spore_pod.xml'],
  'GLUE_SHOT': ['data/entities/projectiles/deck/glue_shot.xml'],
  'BOMB_HOLY': ['data/entities/projectiles/bomb_holy.xml'],
  'BOMB_HOLY_GIGA': ['data/entities/projectiles/bomb_holy_giga.xml'],
  'PROPANE_TANK': ['data/entities/projectiles/propane_tank.xml'],
  'BOMB_CART': ['data/entities/projectiles/bomb_cart.xml'],
  'CURSED_ORB': ['data/entities/projectiles/orb_cursed.xml'],
  'EXPANDING_ORB': ['data/entities/projectiles/orb_expanding.xml'],
  'CRUMBLING_EARTH': ['data/entities/projectiles/deck/crumbling_earth.xml'],
  'SUMMON_ROCK': ['data/entities/projectiles/deck/rock.xml'],
  'SUMMON_EGG': ['data/entities/items/pickup/egg_monster.xml'],
  'SUMMON_HOLLOW_EGG': ['data/entities/items/pickup/egg_hollow.xml'],
  'TNTBOX': ['data/entities/projectiles/deck/tntbox.xml'],
  'TNTBOX_BIG': ['data/entities/projectiles/deck/tntbox_big.xml'],
  'SWARM_FLY': ['data/entities/projectiles/deck/swarm_fly.xml'],
  'SWARM_FIREBUG': ['data/entities/projectiles/deck/swarm_firebug.xml'],
  'SWARM_WASP': ['data/entities/projectiles/deck/swarm_wasp.xml'],
  'FRIEND_FLY': ['data/entities/projectiles/deck/friend_fly.xml'],
  'ACIDSHOT': ['data/entities/projectiles/deck/acidshot.xml'],
  'THUNDERBALL': ['data/entities/projectiles/thunderball.xml'],
  'FIREBOMB': ['data/entities/projectiles/deck/firebomb.xml'],
  'SOILBALL': ['data/entities/projectiles/chunk_of_soil.xml'],
  'DEATH_CROSS': ['data/entities/projectiles/deck/death_cross.xml'],
  'DEATH_CROSS_BIG': ['data/entities/projectiles/deck/death_cross_big.xml'],
  'INFESTATION': ['data/entities/projectiles/deck/infestation.xml'],
  'WALL_HORIZONTAL': ['data/entities/projectiles/deck/wall_horizontal.xml'],
  'WALL_VERTICAL': ['data/entities/projectiles/deck/wall_vertical.xml'],
  'WALL_SQUARE': ['data/entities/projectiles/deck/wall_square.xml'],
  'TEMPORARY_WALL': ['data/entities/projectiles/deck/temporary_wall.xml'],
  'TEMPORARY_PLATFORM': ['data/entities/projectiles/deck/temporary_platform.xml'],
  'PURPLE_EXPLOSION_FIELD': ['data/entities/projectiles/deck/purple_explosion_field.xml'],
  'DELAYED_SPELL': ['data/entities/projectiles/deck/delayed_spell.xml'],
  'LONG_DISTANCE_CAST': ['data/entities/projectiles/deck/long_distance_cast.xml'],
  'TELEPORT_CAST': ['data/entities/projectiles/deck/teleport_cast.xml'],
  'SUPER_TELEPORT_CAST': ['data/entities/projectiles/deck/super_teleport_cast.xml'],
  'CASTER_CAST': ['data/entities/projectiles/deck/caster_cast.xml'],
  'MIST_RADIOACTIVE': ['data/entities/projectiles/deck/mist_radioactive.xml'],
  'MIST_ALCOHOL': ['data/entities/projectiles/deck/mist_alcohol.xml'],
  'MIST_SLIME': ['data/entities/projectiles/deck/mist_slime.xml'],
  'MIST_BLOOD': ['data/entities/projectiles/deck/mist_blood.xml'],
  'CIRCLE_FIRE': ['data/entities/projectiles/deck/circle_fire.xml'],
  'CIRCLE_ACID': ['data/entities/projectiles/deck/circle_acid.xml'],
  'CIRCLE_OIL': ['data/entities/projectiles/deck/circle_oil.xml'],
  'CIRCLE_WATER': ['data/entities/projectiles/deck/circle_water.xml'],
  'MATERIAL_WATER': ['data/entities/projectiles/deck/material_water.xml'],
  'MATERIAL_OIL': ['data/entities/projectiles/deck/material_oil.xml'],
  'MATERIAL_BLOOD': ['data/entities/projectiles/deck/material_blood.xml'],
  'MATERIAL_ACID': ['data/entities/projectiles/deck/material_acid.xml'],
  'MATERIAL_CEMENT': ['data/entities/projectiles/deck/material_cement.xml'],
  'TELEPORT_PROJECTILE': ['data/entities/projectiles/deck/teleport_projectile.xml'],
  'TELEPORT_PROJECTILE_SHORT': ['data/entities/projectiles/deck/teleport_projectile_short.xml'],
  'TELEPORT_PROJECTILE_STATIC': ['data/entities/projectiles/deck/teleport_projectile_static.xml'],
  'SWAPPER_PROJECTILE': ['data/entities/projectiles/deck/swapper.xml'],
  'TELEPORT_PROJECTILE_CLOSER': ['data/entities/projectiles/deck/teleport_projectile_closer.xml'],
  'NUKE': ['data/entities/projectiles/deck/nuke.xml'],
  'NUKE_GIGA': ['data/entities/projectiles/deck/nuke_giga.xml'],
  'FIREWORK': ['data/entities/projectiles/deck/fireworks/firework_pink.xml'],
  'SUMMON_WANDGHOST': ['data/entities/projectiles/deck/wand_ghost_player.xml'],
  'TOUCH_GOLD': ['data/entities/projectiles/deck/touch_gold.xml'],
  'TOUCH_WATER': ['data/entities/projectiles/deck/touch_water.xml'],
  'TOUCH_OIL': ['data/entities/projectiles/deck/touch_oil.xml'],
  'TOUCH_ALCOHOL': ['data/entities/projectiles/deck/touch_alcohol.xml'],
  'TOUCH_PISS': ['data/entities/projectiles/deck/touch_piss.xml'],
  'TOUCH_GRASS': ['data/entities/projectiles/deck/touch_grass.xml'],
  'TOUCH_BLOOD': ['data/entities/projectiles/deck/touch_blood.xml'],
  'TOUCH_SMOKE': ['data/entities/projectiles/deck/touch_smoke.xml'],
  'DESTRUCTION': ['data/entities/projectiles/deck/destruction.xml'],
  'MASS_POLYMORPH': ['data/entities/projectiles/deck/mass_polymorph.xml'],
  'EXPLOSION': ['data/entities/projectiles/deck/explosion.xml'],
  'EXPLOSION_LIGHT': ['data/entities/projectiles/deck/explosion_light.xml'],
  'FIRE_BLAST': ['data/entities/projectiles/deck/fireblast.xml'],
  'POISON_BLAST': ['data/entities/projectiles/deck/poison_blast.xml'],
  'ALCOHOL_BLAST': ['data/entities/projectiles/deck/alcohol_blast.xml'],
  'THUNDER_BLAST': ['data/entities/projectiles/deck/thunder_blast.xml'],
  'BERSERK_FIELD': ['data/entities/projectiles/deck/berserk_field.xml'],
  'POLYMORPH_FIELD': ['data/entities/projectiles/deck/polymorph_field.xml'],
  'CHAOS_POLYMORPH_FIELD': ['data/entities/projectiles/deck/chaos_polymorph_field.xml'],
  'ELECTROCUTION_FIELD': ['data/entities/projectiles/deck/electrocution_field.xml'],
  'FREEZE_FIELD': ['data/entities/projectiles/deck/freeze_field.xml'],
  'REGENERATION_FIELD': ['data/entities/projectiles/deck/regeneration_field.xml'],
  'TELEPORTATION_FIELD': ['data/entities/projectiles/deck/teleportation_field.xml'],
  'LEVITATION_FIELD': ['data/entities/projectiles/deck/levitation_field.xml'],
  'SHIELD_FIELD': ['data/entities/projectiles/deck/shield_field.xml'],
  'PROJECTILE_TRANSMUTATION_FIELD': ['data/entities/projectiles/deck/projectile_transmutation_field.xml'],
  'PROJECTILE_THUNDER_FIELD': ['data/entities/projectiles/deck/projectile_thunder_field.xml'],
  'PROJECTILE_GRAVITY_FIELD': ['data/entities/projectiles/deck/projectile_gravity_field.xml'],
  'VACUUM_POWDER': ['data/entities/projectiles/deck/vacuum_powder.xml'],
  'VACUUM_LIQUID': ['data/entities/projectiles/deck/vacuum_liquid.xml'],
  'VACUUM_ENTITIES': ['data/entities/projectiles/deck/vacuum_entities.xml'],
  'SEA_LAVA': ['data/entities/projectiles/deck/sea_lava.xml'],
  'SEA_ALCOHOL': ['data/entities/projectiles/deck/sea_alcohol.xml'],
  'SEA_OIL': ['data/entities/projectiles/deck/sea_oil.xml'],
  'SEA_WATER': ['data/entities/projectiles/deck/sea_water.xml'],
  'SEA_SWAMP': ['data/entities/projectiles/deck/sea_swamp.xml'],
  'SEA_ACID': ['data/entities/projectiles/deck/sea_acid.xml'],
  'SEA_ACID_GAS': ['data/entities/projectiles/deck/sea_acid_gas.xml'],
  'SEA_MIMIC': ['data/entities/projectiles/deck/sea_mimic.xml'],
  'CLOUD_WATER': ['data/entities/projectiles/deck/cloud_water.xml'],
  'CLOUD_OIL': ['data/entities/projectiles/deck/cloud_oil.xml'],
  'CLOUD_BLOOD': ['data/entities/projectiles/deck/cloud_blood.xml'],
  'CLOUD_ACID': ['data/entities/projectiles/deck/cloud_acid.xml'],
  'CLOUD_THUNDER': ['data/entities/projectiles/deck/cloud_thunder.xml'],
  'X_RAY': ['data/entities/projectiles/deck/xray.xml'],
  'OCARINA_A': ['data/entities/projectiles/deck/ocarina/ocarina_a.xml'],
  'OCARINA_B': ['data/entities/projectiles/deck/ocarina/ocarina_b.xml'],
  'OCARINA_C': ['data/entities/projectiles/deck/ocarina/ocarina_c.xml'],
  'OCARINA_D': ['data/entities/projectiles/deck/ocarina/ocarina_d.xml'],
  'OCARINA_E': ['data/entities/projectiles/deck/ocarina/ocarina_e.xml'],
  'OCARINA_F': ['data/entities/projectiles/deck/ocarina/ocarina_f.xml'],
  'OCARINA_GSHARP': ['data/entities/projectiles/deck/ocarina/ocarina_gsharp.xml'],
  'OCARINA_A2': ['data/entities/projectiles/deck/ocarina/ocarina_a2.xml'],
  'KANTELE_A': ['data/entities/projectiles/deck/kantele/kantele_a.xml'],
  'KANTELE_D': ['data/entities/projectiles/deck/kantele/kantele_d.xml'],
  'KANTELE_DIS': ['data/entities/projectiles/deck/kantele/kantele_dis.xml'],
  'KANTELE_E': ['data/entities/projectiles/deck/kantele/kantele_e.xml'],
  'KANTELE_G': ['data/entities/projectiles/deck/kantele/kantele_g.xml'],
  'METEOR_RAIN': ['data/entities/projectiles/deck/meteor_rain_meteor.xml'],
  'WORM_RAIN': ['data/entities/animals/worm_big.xml'],
} as const;

/* vim: set readonly: Auto-generated file */