/* Auto-generated file */

export const sprites = [
  'var(--sprite-cursor-caret-line)',
  'var(--sprite-cursor-caret-hint-line)',
  'var(--sprite-cursor-spell-over-line)',
  'var(--sprite-cursor-select-over-line)',
  'var(--sprite-cursor-caret-arrow-mid-toright)',
  'var(--sprite-cursor-caret-arrow-mid-toleft)',
  'var(--sprite-cursor-caret-select-mid-toright)',
  'var(--sprite-cursor-caret-select-mid-toleft)',
  'var(--sprite-cursor-caret-select-mid-toleftandright)',
  'var(--sprite-cursor-caret-select-mid-fromright)',
  'var(--sprite-cursor-caret-select-mid-fromleft)',
  'var(--sprite-cursor-caret-select-mid-fromleftandright)',
  'var(--sprite-cursor-caret-select-mid-fromlefttoright)',
  'var(--sprite-cursor-caret-select-mid-fromrighttoleft)',
  'var(--sprite-cursor-caret-spell-mid-toright)',
  'var(--sprite-cursor-caret-spell-mid-toleft)',
  'var(--sprite-cursor-caret-spell-mid-toleftandright)',
  'var(--sprite-cursor-caret-spell-mid-fromright)',
  'var(--sprite-cursor-caret-spell-mid-fromleft)',
  'var(--sprite-cursor-caret-spell-mid-fromleftandright)',
  'var(--sprite-cursor-caret-bottom)',
  'var(--sprite-cursor-caret-top)',
  'var(--sprite-cursor-caret-bottom-2)',
  'var(--sprite-cursor-caret-top-2)',
  'var(--sprite-cursor-caret-hint-bottom)',
  'var(--sprite-cursor-caret-hint-top)',
  'var(--sprite-cursor-caret-hint-top-toright)',
  'var(--sprite-cursor-caret-hint-top-toleft)',
  'var(--sprite-cursor-caret-hint-bottom-toright)',
  'var(--sprite-cursor-caret-hint-bottom-toleft)',
  'var(--sprite-cursor-caret-arrow-top-toright)',
  'var(--sprite-cursor-caret-arrow-top-toleft)',
  'var(--sprite-cursor-caret-arrow-bottom-toright)',
  'var(--sprite-cursor-caret-arrow-bottom-toleft)',
  'var(--sprite-cursor-caret-select-bottom)',
  'var(--sprite-cursor-caret-select-top)',
  'var(--sprite-cursor-caret-select-start-bottom)',
  'var(--sprite-cursor-caret-select-start-top)',
  'var(--sprite-cursor-caret-select-end-bottom)',
  'var(--sprite-cursor-caret-select-end-top)',
  'var(--sprite-cursor-caret-spell-bottom)',
  'var(--sprite-cursor-caret-spell-top)',
  'var(--sprite-cursor-caret-spell-drophint-bottom)',
  'var(--sprite-cursor-caret-spell-drophint-top)',
] as const;

export type Sprite = typeof sprites[number];